services:
  - type: web
    name: omni-translator-app
    runtime: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    rootDir: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: ALLOWED_ORIGINS
        value: https://omni-translator-app.onrender.com
